### ISSUE TITLE
Hellow

### ISSUE THREAD

**Issue by oageo** [ZDK-UTsukuba/ipc-training-2023#3]
@Lailai0477 What mean of "hellow" on 8010d1a1473983c0a5f0228057953c0394718fbc ?

I am guessing the words you wanted to use were: 
* hello: こんにちは
* hollow: 中が空洞の
* hellow: 神聖な

I would appreciate it if you could check and correct this problem.

**Comment by takum1-me** [comment]
@oageo What does mean " What mean of "Hellow" on https://github.com/ZDK-UTsukuba/ipc-training-2023/commit/8010d1a1473983c0a5f0228057953c0394718fbc ? "

I guess what you wanted to say was:

- What does mean  ~ ?
- What's the meaning of ~ ?

I would appreciate it if you would check and correct the word.

**Comment by oageo** [comment]
Thanks for your reply.
I speak mostly Japanese, so I often speak broken English. And I would like to continue learning English!

**Comment by oageo** [comment]
Thanks!
